// <auto-generated />
using System;
using BlueWaveHotel.Entities.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlueWaveHotel.Entities.Migrations
{
    [DbContext(typeof(mySqlContext))]
    [Migration("20240930093936_initDB")]
    partial class initDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BedTypeRoom", b =>
                {
                    b.Property<string>("bedTypesId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("roomsId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("bedTypesId", "roomsId");

                    b.HasIndex("roomsId");

                    b.ToTable("BedTypeRoom");

                    b.HasData(
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "1"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "2"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "3"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "4"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "5"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "6"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "7"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "8"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "9"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "10"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "11"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "12"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "13"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "14"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "15"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "16"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "17"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "18"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "19"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "20"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "21"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "22"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "23"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "24"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "25"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "26"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "27"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "28"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "29"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "30"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "31"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "32"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "33"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "34"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "35"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "36"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "37"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "38"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "39"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "40"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "41"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "42"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "43"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "44"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "45"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "46"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "47"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "48"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "49"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "50"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "50"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "51"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "51"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "52"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "52"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "53"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "53"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "54"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "54"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "55"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "55"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "56"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "56"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "57"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "57"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "58"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "58"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "59"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "59"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "60"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "61"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "62"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "63"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "64"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "65"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "66"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "67"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "68"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "69"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "70"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "70"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "71"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "71"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "72"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "72"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "73"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "73"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "74"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "74"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "75"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "75"
                        },
                        new
                        {
                            bedTypesId = "2",
                            roomsId = "76"
                        },
                        new
                        {
                            bedTypesId = "1",
                            roomsId = "76"
                        },
                        new
                        {
                            bedTypesId = "4",
                            roomsId = "77"
                        },
                        new
                        {
                            bedTypesId = "3",
                            roomsId = "77"
                        });
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.BedType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("bedTypes");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            BedName = "Single",
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 441, DateTimeKind.Local).AddTicks(6802)
                        },
                        new
                        {
                            Id = "2",
                            BedName = "Double",
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 441, DateTimeKind.Local).AddTicks(6817)
                        },
                        new
                        {
                            Id = "3",
                            BedName = "Single-L",
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 441, DateTimeKind.Local).AddTicks(6818)
                        },
                        new
                        {
                            Id = "4",
                            BedName = "Double-L",
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 441, DateTimeKind.Local).AddTicks(6819)
                        });
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Customers", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Id_Number")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Number")
                        .IsUnique();

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.HasIndex("NickName")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("customers");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Extra", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("customerIdId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("fee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("customerIdId");

                    b.ToTable("extras");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Floor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FloorNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("floors");

                    b.HasData(
                        new
                        {
                            Id = "z",
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 442, DateTimeKind.Local).AddTicks(4703),
                            FloorNumber = "z"
                        },
                        new
                        {
                            Id = "1",
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 442, DateTimeKind.Local).AddTicks(4718),
                            FloorNumber = "1"
                        },
                        new
                        {
                            Id = "2",
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 442, DateTimeKind.Local).AddTicks(4719),
                            FloorNumber = "2"
                        },
                        new
                        {
                            Id = "3",
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 442, DateTimeKind.Local).AddTicks(4720),
                            FloorNumber = "3"
                        },
                        new
                        {
                            Id = "4",
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 442, DateTimeKind.Local).AddTicks(4722),
                            FloorNumber = "4"
                        });
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Package", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<decimal>("fee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("packageName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("packageName")
                        .IsUnique();

                    b.ToTable("packages");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Personel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ID_number")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("professionId")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("salaryTypeIdId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ID_number")
                        .IsUnique();

                    b.HasIndex("NickName")
                        .IsUnique();

                    b.HasIndex("password")
                        .IsUnique();

                    b.HasIndex("professionId");

                    b.HasIndex("salaryTypeIdId");

                    b.ToTable("personels");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProductCategoriesId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoriesId");

                    b.HasIndex("ProductName")
                        .IsUnique();

                    b.ToTable("products");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.ProductCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("productCategories");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Profession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("professions");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Reservation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("BookingEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("BookingStart")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Purchase")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("customersId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("packageId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("customersId");

                    b.HasIndex("packageId");

                    b.ToTable("reservations");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Room", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("ReservationId1")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("floorID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId1");

                    b.HasIndex("floorID");

                    b.ToTable("rooms");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(121),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "2",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(452),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "3",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(567),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "4",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(686),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "5",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(786),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "6",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(887),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "7",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(994),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "8",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(1093),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "9",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(1191),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "10",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(1294),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "11",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(1410),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "12",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(1512),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "13",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(1608),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "14",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(1704),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "15",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(1808),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "16",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(1905),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "17",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(2001),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "18",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(2110),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "19",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(2209),
                            Status = "avaible",
                            floorID = "1"
                        },
                        new
                        {
                            Id = "20",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(2305),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "21",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(2408),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "22",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(2514),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "23",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(2611),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "24",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(2710),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "25",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(2807),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "26",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(2911),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "27",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(3008),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "28",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(3107),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "29",
                            Capacity = 1,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(3211),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "30",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(3311),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "31",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(3418),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "32",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(3520),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "33",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(3626),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "34",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(3728),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "35",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(3826),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "36",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(3933),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "37",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(4031),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "38",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(4128),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "39",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(4225),
                            Status = "avaible",
                            floorID = "2"
                        },
                        new
                        {
                            Id = "40",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(4331),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "41",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(4437),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "42",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(4535),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "43",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(4632),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "44",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(4735),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "45",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(4832),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "46",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(4929),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "47",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(5031),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "48",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(5129),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "49",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(5227),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "50",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(5324),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "51",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(5440),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "52",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(5545),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "53",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(5644),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "54",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(5746),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "55",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(5856),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "56",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(5957),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "57",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(6055),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "58",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(6162),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "59",
                            Capacity = 3,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(6262),
                            Status = "avaible",
                            floorID = "3"
                        },
                        new
                        {
                            Id = "60",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(6364),
                            Status = "avaible",
                            floorID = "4"
                        },
                        new
                        {
                            Id = "61",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(6471),
                            Status = "avaible",
                            floorID = "4"
                        },
                        new
                        {
                            Id = "62",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(6579),
                            Status = "avaible",
                            floorID = "4"
                        },
                        new
                        {
                            Id = "63",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(6680),
                            Status = "avaible",
                            floorID = "4"
                        },
                        new
                        {
                            Id = "64",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(6780),
                            Status = "avaible",
                            floorID = "4"
                        },
                        new
                        {
                            Id = "65",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(6888),
                            Status = "avaible",
                            floorID = "4"
                        },
                        new
                        {
                            Id = "66",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(6989),
                            Status = "avaible",
                            floorID = "4"
                        },
                        new
                        {
                            Id = "67",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(7084),
                            Status = "avaible",
                            floorID = "4"
                        },
                        new
                        {
                            Id = "68",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(7181),
                            Status = "avaible",
                            floorID = "4"
                        },
                        new
                        {
                            Id = "69",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(7290),
                            Status = "avaible",
                            floorID = "4"
                        },
                        new
                        {
                            Id = "70",
                            Capacity = 4,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(7393),
                            Status = "avaible",
                            floorID = "4"
                        },
                        new
                        {
                            Id = "71",
                            Capacity = 4,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(7498),
                            Status = "avaible",
                            floorID = "4"
                        },
                        new
                        {
                            Id = "72",
                            Capacity = 4,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(7607),
                            Status = "avaible",
                            floorID = "4"
                        },
                        new
                        {
                            Id = "73",
                            Capacity = 4,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(7709),
                            Status = "avaible",
                            floorID = "4"
                        },
                        new
                        {
                            Id = "74",
                            Capacity = 4,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(7809),
                            Status = "avaible",
                            floorID = "4"
                        },
                        new
                        {
                            Id = "75",
                            Capacity = 4,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(7909),
                            Status = "avaible",
                            floorID = "4"
                        },
                        new
                        {
                            Id = "76",
                            Capacity = 4,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(8016),
                            Status = "avaible",
                            floorID = "4"
                        },
                        new
                        {
                            Id = "77",
                            Capacity = 2,
                            CreatedTime = new DateTime(2024, 9, 30, 12, 39, 35, 444, DateTimeKind.Local).AddTicks(8114),
                            Status = "avaible",
                            floorID = "4"
                        });
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.SalaryType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("salaryTypes");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Shift", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Finish")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Start")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("shifts");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.TimeTracking", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Finish")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("timeTrackings");
                });

            modelBuilder.Entity("ExtraProduct", b =>
                {
                    b.Property<string>("extrasId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("productId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("extrasId", "productId");

                    b.HasIndex("productId");

                    b.ToTable("ExtraProduct");
                });

            modelBuilder.Entity("PersonelShift", b =>
                {
                    b.Property<string>("PersonelsId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("shiftsId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("PersonelsId", "shiftsId");

                    b.HasIndex("shiftsId");

                    b.ToTable("PersonelShift");
                });

            modelBuilder.Entity("PersonelTimeTracking", b =>
                {
                    b.Property<string>("MyPropertyId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("personelsId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("MyPropertyId", "personelsId");

                    b.HasIndex("personelsId");

                    b.ToTable("PersonelTimeTracking");
                });

            modelBuilder.Entity("ProfessionShift", b =>
                {
                    b.Property<string>("ShiftId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("professionsId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ShiftId", "professionsId");

                    b.HasIndex("professionsId");

                    b.ToTable("ProfessionShift");
                });

            modelBuilder.Entity("BedTypeRoom", b =>
                {
                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.BedType", null)
                        .WithMany()
                        .HasForeignKey("bedTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.Room", null)
                        .WithMany()
                        .HasForeignKey("roomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Extra", b =>
                {
                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.Customers", "customerId")
                        .WithMany()
                        .HasForeignKey("customerIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customerId");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Personel", b =>
                {
                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.Profession", "profession")
                        .WithMany("personels")
                        .HasForeignKey("professionId");

                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.SalaryType", "salaryTypeId")
                        .WithMany("Personels")
                        .HasForeignKey("salaryTypeIdId");

                    b.Navigation("profession");

                    b.Navigation("salaryTypeId");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Product", b =>
                {
                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.ProductCategory", "ProductCategories")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Reservation", b =>
                {
                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.Customers", "customers")
                        .WithMany()
                        .HasForeignKey("customersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.Package", "package")
                        .WithMany("reservations")
                        .HasForeignKey("packageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customers");

                    b.Navigation("package");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Room", b =>
                {
                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.Reservation", "Reservation")
                        .WithMany("roomsId")
                        .HasForeignKey("ReservationId1");

                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.Floor", "floor")
                        .WithMany("rooms")
                        .HasForeignKey("floorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("floor");
                });

            modelBuilder.Entity("ExtraProduct", b =>
                {
                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.Extra", null)
                        .WithMany()
                        .HasForeignKey("extrasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.Product", null)
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonelShift", b =>
                {
                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.Personel", null)
                        .WithMany()
                        .HasForeignKey("PersonelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.Shift", null)
                        .WithMany()
                        .HasForeignKey("shiftsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonelTimeTracking", b =>
                {
                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.TimeTracking", null)
                        .WithMany()
                        .HasForeignKey("MyPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.Personel", null)
                        .WithMany()
                        .HasForeignKey("personelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProfessionShift", b =>
                {
                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.Shift", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlueWaveHotel.Entities.Model.Concrete.Profession", null)
                        .WithMany()
                        .HasForeignKey("professionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Floor", b =>
                {
                    b.Navigation("rooms");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Package", b =>
                {
                    b.Navigation("reservations");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Profession", b =>
                {
                    b.Navigation("personels");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.Reservation", b =>
                {
                    b.Navigation("roomsId");
                });

            modelBuilder.Entity("BlueWaveHotel.Entities.Model.Concrete.SalaryType", b =>
                {
                    b.Navigation("Personels");
                });
#pragma warning restore 612, 618
        }
    }
}
